ifneq ($(HOST),$(TARGET))
CC ?= $(TARGET)-gcc
AR ?= $(TARGET)-ar
else
CC ?= gcc
AR ?= ar
endif

ifneq ("$(MSYSTEM)","")
OUT_DIR := $(shell cygpath "$(OUT_DIR)")
endif

.PHONY: all
all: $(OUT_DIR)/libtinyfiledialogs.a

$(OUT_DIR)/tinyfiledialogs.o: libtinyfiledialogs/tinyfiledialogs.c $(CURDIR)/makefile.cargo
	mkdir -p `dirname $@` && $(CC) $< -o $@ -c $(CXXFLAGS) -fPIC 

$(OUT_DIR)/libtinyfiledialogs.a: $(OUT_DIR)/tinyfiledialogs.o
	$(AR) rcs $@ $(OUT_DIR)/tinyfiledialogs.o
